name: Deploy to Prod
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  deploy:
    env:
      NAMESPACE: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Dependencies CDK
        run: npm install -g aws-cdk
        working-directory: ./rest-api-hello-world
      
      - name: Install Dependencies
        run: npm install
        working-directory: ./rest-api-hello-world

      - name: Deploy CDK
        run: cdk deploy
        working-directory: ./rest-api-hello-world